[tool.poetry]
name = "diary-diploma"
version = "0.1.0"
description = ""
authors = ["Swetlana Mirzoeva <levka008@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^6.0.3"
djangorestframework = "^3.16.1"
django-cors-headers = "^4.9.0"
psycopg2-binary = "^2.9.11"
djangorestframework-simplejwt = "^5.5.1"
drf-yasg = "^1.21.15"
python-decouple = "^3.8"


[tool.poetry.group.lint.dependencies]
isort = "^8.0.1"
black = "^26.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
